name: Github / Asana Workflow

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
        - name: Create Asana ticket
          env:
            ISSUE_TITLE: ${{ github.event.issue.title }}
            ISSUE_BODY: ${{ github.event.issue.body }}
            ISSUE_HTML_URL: ${{ github.event.issue.html_url }}
            ISSUE_ID: ${{ github.event.issue.id }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
          run: |
            JSON_BODY=$(jq -n \
              --arg title "$ISSUE_TITLE" \
              --arg body "$ISSUE_BODY" \
              --arg url "$ISSUE_HTML_URL" \
              --arg id "$ISSUE_ID" \
              --arg number "$ISSUE_NUMBER" \
              '{
                "data": {
                  "custom_fields": {
                    "1208961704779581": "1208961704779582",
                    "1208961704779592": "1208961704779596",
                    "1208779519954980": "1208779521616959",
                    "1210103546117753": "1210103546117756",
                    "1210347857768758": $url
                  },
                  "name": $title,
                  "workspace": "780103692902078",
                  "projects": ["1208970714650308"],
                  "assignee_section": "1208970755434051",
                  "notes": "Issue ID: \($id)\nIssue number: \($number)\nCreated via GitHub Actions\n----\n\n\($body)"
                }
              }')

            curl --request POST \
                 --url https://app.asana.com/api/1.0/tasks?opt_pretty=true \
                 --header 'accept: application/json' \
                 --header 'authorization: Bearer ${{ secrets.ASANA_PAT }}' \
                 --header 'content-type: application/json' \
                 --data "$JSON_BODY"
