name: Github / Asana Workflow

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
        - name: Get Asana Task Corresponding to Issue
          env:
            ISSUE_ID: ${{ github.event.issue.id }}
          run: |
            curl --request GET \
                 --url "https://app.asana.com/api/1.0/workspaces/780103692902078/tasks/search?opt_fields=notes,custom_fields.text_value&text=$ISSUE_ID&sort_by=modified_at&sort_ascending=false" \
                 --header 'accept: application/json' \
                 --header 'authorization: Bearer ${{ secrets.ASANA_PAT }}'
                 --output response.json
            TASK_GID=$(jq -r '.data.gid' response.json)
            echo "TASK_GID=$TASK_GID" >> $GITHUB_ENV

        - name: Comment on Asana Task
          env:
            ISSUE_COMMENT: ${{ github.event.comment.body }}
          run: |
            BODY_DATA=$(jq -n \
              --arg text "$ISSUE_COMMENT" \
              '{
                "data": {
                  "text": $text
                }
              }')
            curl --request POST \
                 --url https://app.asana.com/api/1.0/tasks/$TASK_GID/stories \
                 --header 'accept: application/json' \
                 --header 'authorization: Bearer ${{ secrets.ASANA_PAT }}' \
                 --header 'content-type: application/json' \
                 --data "$BODY_DATA"